# -*- coding: utf-8 -*-
REF = (23.10344, 113.35412)  # China Import & Export Fair Complex, Yuejiang Zhong Rd

V = [
{"id":"press-centre","rank":1,"name":"Canton Fair Complex · Official Press & Media Centre","cn":"广交会展馆 新闻中心（A区）",
 "zone":"Inside the halls","addr":"Area A, China Import & Export Fair Complex, 380 Yuejiang Zhong Rd, Haizhu","ll":(23.10344,113.35412),
 "walk":"0 min, inside the venue","backdrop":"Canton Fair branding wall, hall floor through glass",
 "why":"The organiser's own press centre. Cheapest credibility in the building: accredited media are already there, and a guest walks in off the hall floor with a badge. Best for a same-day sit-down with a trade journalist.",
 "watch":"Controlled by China Foreign Trade Centre, so you get a slot, not a set. No branding freedom, no exclusivity, and no Canton Tower in shot.",
 "tags":["Free/accredited","Zero travel","No branding control"],
 "imgq":["Canton Fair Guangzhou","Canton Fair exhibition"],
 "commons":["Canton_Fair_Complex_Area_A_and_Canton_Fair_Building.jpg"]},

{"id":"area-d","rank":8,"name":"Canton Fair Complex · Area D (Phase IV) conference rooms","cn":"广交会展馆四期 会议区",
 "zone":"Inside the halls","addr":"Area D (Phase IV), China Import & Export Fair Complex, Pazhou","ll":(23.1032,113.3470),
 "walk":"3–8 min walk inside the complex","backdrop":"New-build glass atrium, daylight, hall traffic behind",
 "why":"The newest wing of the complex, opened for the 135th session. Bigger, brighter conference rooms than the legacy halls and easier to dress. Good if you want the interview to visibly happen at the fair.",
 "watch":"Allocation goes through the fair organiser and fills early. Confirm which rooms take a two-camera set and whether you can rig lights.",
 "tags":["Inside venue","Daylight","Organiser-allocated"],
 "imgq":["Canton Fair Complex","Pazhou exhibition Guangzhou"],
 "commons":["Guangzhou_Pazhou_Poly_Plaza.jpg","Pazhou_West.jpg"]},

{"id":"westin","rank":3,"name":"The Westin Pazhou","cn":"广交会威斯汀酒店",
 "zone":"Attached to the complex","addr":"681 Fengpu Zhong Rd, Pazhou, Haizhu","ll":(23.09870,113.35817),
 "walk":"Connected, approx. 0.7 km, covered route","backdrop":"Top-floor Prego with Pearl River and skyline; ballroom pre-function for a branded wall",
 "why":"Sits at Area C of the complex and is where a lot of senior buyers actually stay. A suite or the top-floor restaurant gives you a private room plus a high-floor window without anyone leaving the site.",
 "watch":"Peak fair weeks: rooms go to the hotel's own corporate bookings months out. Lock a suite in a single booking with the F&B space.",
 "tags":["Connected to venue","5-star","High floor"],
 "imgq":["Westin Pazhou Guangzhou","Westin hotel Guangzhou"],
 "commons":["Pazhou_Central_Area_and_Pazhou_West_Area.jpg"]},

{"id":"langham","rank":2,"name":"Langham Place, Guangzhou","cn":"广州南丰朗豪酒店",
 "zone":"Across the street","addr":"638 Xingang East Rd, Pazhou, Haizhu","ll":(23.09947,113.35459),
 "walk":"approx. 0.4 km · 5 min walk","backdrop":"Rooftop bar at night; Great Hall for a dressed set",
 "why":"Directly opposite the complex, on top of the Nan Fung exhibition podium. The rooftop bar is the single easiest 'drinks-and-camera' set-up in Pazhou: you can run panel interviews by day in a function room and move the same guests upstairs for the evening piece.",
 "watch":"Rooftop is weather-dependent and shared with hotel guests unless you buy it out. Get the buy-out price before you build the run-of-show.",
 "tags":["5 min walk","Rooftop bar","Function rooms"],
 "imgq":["Langham Place Guangzhou","Langham Guangzhou hotel"],
 "commons":["Nan_Fung_International_Convention_&_Exhibition_Center_20230519-01.jpg"]},

{"id":"nicec","rank":11,"name":"Nan Fung International Convention & Exhibition Centre (NICEC)","cn":"南丰国际会展中心",
 "zone":"Across the street","addr":"630–638 Xingang East Rd, next to Xingang Dong station Exit F","ll":(23.09947,113.35459),
 "walk":"approx. 0.4 km · 5 min walk","backdrop":"Blank-canvas hall: build the set you want",
 "why":"Four halls, 25,000 sqm, in the same podium as Langham Place. Take a corner of a hall and build a proper studio: black drape, LED wall, two sets, holding room. This is the option if you want the media room to look like WorldFirst, not like a hotel.",
 "watch":"Build cost and rigging time. You are paying for square metres and a crew, not a ready room. Needs a 2-day bump-in.",
 "tags":["Build your own set","5 min walk","Metro Exit F"],
 "imgq":["Nan Fung Guangzhou","exhibition hall Guangzhou"],
 "commons":["Nan_Fung_International_Convention_&_Exhibition_Center_20230519-02.jpg","Nan_Fung_International_Convention_&_Exhibition_Center_20230519-01.jpg"]},

{"id":"courtyard","rank":12,"name":"Courtyard by Marriott Guangzhou Pazhou","cn":"广交会万怡酒店",
 "zone":"Attached to the complex","addr":"Fengpu Zhong Rd, Pazhou, Haizhu","ll":(23.09895,113.35625),
 "walk":"approx. 0.5 km · direct connection to the complex","backdrop":"Neutral meeting rooms, easy to brand",
 "why":"The pragmatic backup. Direct connectivity to the halls, meeting rooms at a fraction of the five-star rate, and enough of them that you can hold two in parallel: one for interviews, one as a green room.",
 "watch":"No view and no wow. Only worth it if the story is the guest, not the city.",
 "tags":["Budget-sane","Connected","Multiple rooms"],
 "imgq":["Courtyard Marriott Guangzhou","Guangzhou hotel meeting room"],
 "commons":["Pearl_River_side_in_Guangzhou_Pazhou_20220930-02.jpg"]},

{"id":"poly-wtc","rank":10,"name":"Poly World Trade Center Expo Hall","cn":"保利世贸博览馆",
 "zone":"Next door","addr":"1000 Xingang East Rd, connected to Pazhou metro station","ll":(23.09991,113.36229),
 "walk":"approx. 0.9 km · 12 min walk / 1 metro stop","backdrop":"Modern expo architecture, high ceilings",
 "why":"Six exhibition halls plus a metro-level hall, connected directly to Pazhou station. Same blank-canvas logic as NICEC but with its own metro entrance, which matters when you are moving guests during fair rush hour.",
 "watch":"Often booked by its own concurrent shows during Canton Fair weeks. Check the hall calendar before you plan anything.",
 "tags":["Metro-connected","Large format","Own calendar"],
 "imgq":["Poly World Trade Center Guangzhou"],
 "commons":["Poly_World_Trade_Center_Expo_Hall_20230726-05.jpg","Poly_World_Trade_Center_20230217-01.jpg","Poly_World_Trade_Center_Exterior_20230726.jpg"]},

{"id":"intercon","rank":4,"name":"InterContinental Guangzhou Exhibition Center","cn":"广州保利洲际酒店",
 "zone":"Next door","addr":"828 Xingang East Rd, Poly Skyline Plaza, Pazhou","ll":(23.09960,113.36200),
 "walk":"approx. 0.9 km · 12 min walk / 3 min drive","backdrop":"River-facing ballroom foyer with a glass wall onto the Pearl River",
 "why":"1,800 sqm pillarless ballroom with natural light, a 500 sqm second ballroom and 11 multi-function rooms, and the foyer looks out over the Pearl River. Enough rooms to run a media room, a green room and a partner meeting room off one foyer all day.",
 "watch":"It is a working convention hotel during the fair, so confirm you are not sharing the foyer with someone else's coffee break.",
 "tags":["River-facing foyer","11 breakout rooms","Adjacent to venue"],
 "imgq":["InterContinental Guangzhou","Poly Guangzhou hotel"],
 "commons":["Poly_World_Trade_Center_20230217-02.jpg","Guangzhou_Pazhou_Poly_Plaza.jpg"]},

{"id":"shangri-la","rank":5,"name":"Shangri-La Hotel, Guangzhou","cn":"广州香格里拉大酒店",
 "zone":"Across the footbridge","addr":"1 Huizhan East Rd, Pazhou, Haizhu","ll":(23.1040,113.3601),
 "walk":"approx. 0.6 km · covered footbridge to Area A","backdrop":"River-view rooms and riverside terrace; Canton Tower visible up-river on a clear day",
 "why":"The default 'serious meeting' hotel for Canton Fair. Covered walkway straight into Area A, river-facing function rooms, and the staff have run press for the fair for twenty years. Lowest-risk five-star option.",
 "watch":"The most requested hotel in Pazhou during the fair. If you want this, book it before you finalise the guest list.",
 "tags":["Footbridge to Area A","River view","Press-experienced"],
 "imgq":["Shangri-La Guangzhou","Guangzhou Shangri-La hotel"],
 "commons":["Guangzhou_Shagri-La_Hotel.jpg","Guangzhou_Poly_International_Plaza,_Guangzhou_Shangri-La_Hotel_and_Canton_Tower.jpg"]},

{"id":"sourcing-centre","rank":14,"name":"Guangzhou International Sourcing Centre","cn":"广州国际采购中心",
 "zone":"Pazhou island","addr":"Pazhou Da Dao East, Haizhu","ll":(23.10260,113.36544),
 "walk":"approx. 1.2 km · 5 min drive","backdrop":"Trade-floor architecture, corporate and neutral",
 "why":"Purpose-built sourcing and exhibition building next to the fair. Conference space that is cheaper and quieter than the hotels, and the building itself says 'trade' on camera, which fits the WorldFirst story.",
 "watch":"Less hospitality polish, so you bring your own catering, comfort and signage.",
 "tags":["On-message backdrop","Quieter","BYO production"],
 "imgq":["Guangzhou International Sourcing Centre"],
 "commons":["Guangzhou_International_Sourcing_Centre_20230217.jpg","Guangzhou_International_Sourcing_Centre_20230623-02.jpg"]},

{"id":"ferry","rank":9,"name":"Pazhou Ferry Terminal riverside deck","cn":"琶洲码头 珠江岸边",
 "zone":"Pazhou island","addr":"Yuejiang Zhong Rd riverfront, north of the complex","ll":(23.1065,113.3585),
 "walk":"approx. 0.5 km · 7 min walk","backdrop":"Open Pearl River, ferries, Canton Tower up-river at dusk",
 "why":"Free, outdoors, and two minutes from Area A. The strongest cheap option for a walk-and-talk or a stand-up piece with real river traffic behind the guest. Golden hour here is the best-value shot in Pazhou.",
 "watch":"Public space: permits for tripods and crew, no power, no weather cover, and the light window is about forty minutes.",
 "tags":["Free","Outdoor","Golden hour"],
 "imgq":["Pazhou ferry Guangzhou","Pearl River Guangzhou"],
 "commons":["Exterior,_Pazhou_Ferry_Terminal,_Guangzhou_20230701-B.jpg","Exterior,_Pazhou_Ferry_Terminal,_Guangzhou_20241019.jpg"]},

{"id":"ali-center","rank":7,"name":"Ali Center / Pazhou West AI & Digital Economy District","cn":"阿里巴巴华南营运中心 · 琶洲西区",
 "zone":"Pazhou island","addr":"Dingxin Rd, Pazhou West, Haizhu","ll":(23.10697,113.34223),
 "walk":"approx. 1.3 km · 5 min drive","backdrop":"New-build tech towers, riverside plaza, Canton Tower down-river",
 "why":"Pazhou West is the digital-trade cluster, where Alibaba, Vipshop and Tencent all have towers, and the riverside plaza frames Canton Tower. If the interview is about cross-border digital trade, this is the district that argues the point for you.",
 "watch":"Corporate campuses need a host and a security pass. Treat this as a partner-hosted shoot, not a venue you rent.",
 "tags":["Digital-trade story","Partner-hosted","Riverside plaza"],
 "imgq":["Pazhou Guangzhou skyline","Alibaba Guangzhou"],
 "commons":["Pazhou_West.jpg","Pazhou_Central_Area_and_Pazhou_West_Area.jpg"]},

{"id":"pazhou-bridge","rank":16,"name":"Pazhou Bridge & Yuejiang Rd promenade","cn":"琶洲大桥 · 阅江路江岸",
 "zone":"Pazhou island","addr":"Pazhou Bridge, Yuejiang Rd riverfront","ll":(23.11035,113.36856),
 "walk":"approx. 1.7 km · 6 min drive","backdrop":"Bridge, river and the Financial City skyline across the water",
 "why":"A hard, graphic backdrop for a short piece-to-camera or a title sequence. Use it for B-roll and openers rather than a sit-down.",
 "watch":"Traffic noise kills usable audio. Radio mics and a wind kit, or plan to voice it over.",
 "tags":["B-roll","Free","Noisy"],
 "imgq":["Pazhou bridge Guangzhou"],
 "commons":["Aerial_View,_Pazhou_Bridge,_Guangzhou_20230701-A.jpg","Pazhou_Bridge_20230915.jpg"]},

{"id":"media-port","rank":6,"name":"Guangzhou International Media Port (GRT)","cn":"广州国际媒体港 · 广州广播电视台",
 "zone":"Canton Tower corridor","addr":"218 Yuejiang West Rd, Haizhu (next to Canton Tower)","ll":(23.10852,113.31569),
 "walk":"approx. 4 km · 12 min drive","backdrop":"Real broadcast studios; Canton Tower next door for exteriors",
 "why":"The city broadcaster's own media complex, on the river beside Canton Tower: studios, control rooms, crew and a multi-function performance and broadcast centre. If you want the interviews to look like television rather than a hotel function room, this is the one.",
 "watch":"Booking runs through GRT and likely needs a media partner on the paperwork. Start that conversation now, not in October.",
 "tags":["Real studios","Canton Tower next door","Needs a partner"],
 "imgq":["Guangzhou television Canton Tower","Guangzhou media port"],
 "commons":["Canton_Tower_at_night_Guangzhou_2024_dllu.jpg"]},

{"id":"canton-tower","rank":13,"name":"Canton Tower · observation decks and rotating restaurant","cn":"广州塔 · 观景层 / 旋转餐厅",
 "zone":"Canton Tower corridor","addr":"222 Yuejiang West Rd, Haizhu","ll":(23.10901,113.31915),
 "walk":"approx. 3.6 km · 15 min drive","backdrop":"The whole city, 433 m up, and you are inside the landmark",
 "why":"The backdrop is the landmark itself. The 433 m deck and the 424 m rotating restaurant give a shot nobody can argue with, and the venue has hosted corporate events for years.",
 "watch":"You cannot see Canton Tower from inside Canton Tower. Haze cuts visibility often. Lighting a shot against a glass curtain wall at height needs a proper crew.",
 "tags":["Landmark","High-altitude","Glass reflections"],
 "imgq":["Canton Tower observation deck","Guangzhou TV tower"],
 "commons":["Canton_Tower_-_433M_Sightseeing_Observation_Deck.jpg","Canton_Tower_20241027.jpg"]},

{"id":"party-pier","rank":15,"name":"Party Pier (Pearl River Brewery)","cn":"珠江琶醍啤酒文化创意艺术区",
 "zone":"Canton Tower corridor","addr":"Yuejiang West Rd riverside, Haizhu","ll":(23.11043,113.33423),
 "walk":"approx. 2.3 km · 8 min drive / tram","backdrop":"Converted brewery, riverside terraces, Canton Tower across the water",
 "why":"Industrial brick, riverside terraces and Canton Tower in the background. Informal, creator-friendly, and the venues here are used to cameras. Right for KOL content and the evening social cut, not for a bank economist in a suit.",
 "watch":"It is a nightlife strip, so sound and crowd control after dark are real problems. Shoot the serious stuff before 6pm.",
 "tags":["Creator-friendly","Canton Tower backdrop","Noisy at night"],
 "imgq":["Party Pier Guangzhou","Pearl River Brewery Guangzhou"],
 "commons":["Haixin_Bridge_on_Pearl_River.jpg"]},

{"id":"park-hyatt","rank":17,"name":"Park Hyatt Guangzhou · The Roof Bar (70F)","cn":"广州柏悦酒店 · 顶楼酒吧",
 "zone":"Zhujiang New Town","addr":"Zhujiang New Town, Tianhe","ll":(23.1186,113.3218),
 "walk":"approx. 7 km by road · 20 min drive","backdrop":"Canton Tower head-on from 280 m, open air",
 "why":"The highest rooftop bar in the city, looking straight across the river at Canton Tower. The single best evening establishing shot on this list.",
 "watch":"Twenty minutes each way in fair-week traffic, plus a lift queue. Realistically a one-hour evening window, not a working media room.",
 "tags":["Best evening shot","Open air","Far from venue"],
 "imgq":["Park Hyatt Guangzhou","Guangzhou rooftop bar"],
 "commons":["Zhujiang_New_Town_of_Guangzhou_at_night_01.jpg"]},

{"id":"four-seasons","rank":18,"name":"Four Seasons Hotel Guangzhou (IFC)","cn":"广州四季酒店 · 国际金融中心",
 "zone":"Zhujiang New Town","addr":"5 Zhujiang West Rd, IFC, Tianhe","ll":(23.12043,113.31797),
 "walk":"approx. 8 km by road · 20 min drive","backdrop":"Sky lobby atrium and Canton Tower across the river through floor-to-ceiling glass",
 "why":"High-floor rooms and public spaces look directly at Canton Tower. If a financial-services guest is staying in Zhujiang New Town anyway (and Mastercard or HSBC people usually are), you shoot where they already are.",
 "watch":"Far from Pazhou. Only justifiable if the guest's diary, not yours, sets the location.",
 "tags":["Guest-convenient","Canton Tower view","Far from venue"],
 "imgq":["Four Seasons Guangzhou","Guangzhou IFC"],
 "commons":["Guangzhou_International_Finance_Center.jpg","GZIFC.jpg"]},

{"id":"rosewood","rank":19,"name":"Rosewood Guangzhou (CTF Finance Centre)","cn":"广州瑰丽酒店 · 周大福金融中心",
 "zone":"Zhujiang New Town","addr":"6 Zhujiang East Rd, CTF Finance Centre, Tianhe","ll":(23.1196,113.3255),
 "walk":"approx. 7 km by road · 20 min drive","backdrop":"Sky lobby at 530 m, the highest hotel in southern China",
 "why":"Altitude as a statement. The 93rd-floor pool and sky lobby give a backdrop that reads 'global finance' instantly, which suits an FX or economics conversation.",
 "watch":"Same distance problem, and the hotel is protective of its public spaces. Expect a buy-out conversation.",
 "tags":["530 m","Finance framing","Far from venue"],
 "imgq":["Rosewood Guangzhou","CTF Finance Centre Guangzhou"],
 "commons":["Guangzhou_CTF_Finance_Centre_02-10-2018.jpg"]},

{"id":"haixin","rank":20,"name":"Haixin Bridge & Zhujiang New Town riverfront","cn":"海心桥 · 珠江新城江岸",
 "zone":"Zhujiang New Town","addr":"Haixin Bridge, between Haixinsha and Canton Tower","ll":(23.1140,113.3235),
 "walk":"approx. 6 km by road · 18 min drive","backdrop":"Canton Tower and the full Zhujiang skyline from the pedestrian bridge",
 "why":"The postcard shot of Guangzhou, free, and a five-minute walk from the Canton Tower venues. Use it for the opener and the city cutaways that tie the whole media room package together.",
 "watch":"Pedestrian bridge with timed access and crowds. Permits for professional kit; scout the slot before committing.",
 "tags":["Postcard shot","Free","Permits needed"],
 "imgq":["Haixin bridge Guangzhou","Guangzhou skyline night"],
 "commons":["Haixin_Bridge_on_Pearl_River.jpg","Huacheng_Square_and_Zhujiang_New_Town_skyline,_Guangzhou,_July_2026.jpg"]},
]
